object Versions {
    const val slf4j = "1.7.30"
    const val jackson = "2.11.3"
    const val kotlin = "1.4.10"
    const val logback = "1.2.3"
    const val ktor = "1.4.2"
    const val kotlinLogging = "1.8.3"
    const val kotlinCoroutines = "1.4.1"
    const val awaitility = "4.0.2"
    const val hamkrest = "1.7.0.3"
    const val config4k = "0.4.2"
    const val kotlinSerialization = "1.0.1"
    const val mapdb = "3.0.8"
    const val cloudbeesSyslog = "1.1.7"
    const val jug = "4.0.1"
    const val mockk = "1.10.2"
    const val detekt = "1.14.2"
    const val semverGit = "2.3.0"
    const val testLogger = "2.1.1"
    const val kafka = "2.7.0"
    const val junit = "5.5.2"
    const val commonsValidator = "1.7"
}
